# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_board_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoardRow',
            new_name='Row',
        ),
        migrations.RenameModel(
            old_name='BoardRowSquare',
            new_name='Square',
        ),
    ]
