# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_board_app', '0002_auto_20180226_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building', to='game_board_app.Element'),
        ),
        migrations.AlterField(
            model_name='building',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building', to='users_app.User'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='game_board_app.Game'),
        ),
        migrations.AlterField(
            model_name='row',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row', to='game_board_app.Game'),
        ),
        migrations.AlterField(
            model_name='square',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='square', to='game_board_app.Building'),
        ),
        migrations.AlterField(
            model_name='square',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='square', to='game_board_app.Row'),
        ),
        migrations.AlterField(
            model_name='square',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='square', to='game_board_app.Unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='game_board_app.Element'),
        ),
    ]
