# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_board_app', '0004_auto_20180226_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='game_board_app.Game'),
        ),
        migrations.AlterField(
            model_name='square',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squares', to='game_board_app.Row'),
        ),
    ]
