# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_board_app', '0005_auto_20180226_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='square',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='square', to='game_board_app.Building'),
        ),
        migrations.AlterField(
            model_name='square',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='square', to='game_board_app.Unit'),
        ),
    ]
