# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
        ('game_board_app', '0006_auto_20180226_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='Building', max_length=50)),
                ('level', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity', to='game_board_app.Element')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity', to='users_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='building',
            name='element',
        ),
        migrations.RemoveField(
            model_name='building',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='element',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='square',
            name='building',
        ),
        migrations.RemoveField(
            model_name='square',
            name='status',
        ),
        migrations.RemoveField(
            model_name='square',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.AddField(
            model_name='square',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='square', to='game_board_app.Entity'),
        ),
    ]
