# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_board_app', '0007_auto_20180226_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game_board_app.Game'),
        ),
    ]
