# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_board_app', '0008_auto_20180226_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
