# Generated by Django 2.0.2 on 2018-02-27 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_board_app', '0009_game_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity', to='game_board_app.Element'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity', to='users_app.User'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='game_board_app.Game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users_app.User'),
        ),
        migrations.AlterField(
            model_name='row',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='game_board_app.Game'),
        ),
        migrations.AlterField(
            model_name='square',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='square', to='game_board_app.Entity'),
        ),
        migrations.AlterField(
            model_name='square',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='squares', to='game_board_app.Row'),
        ),
    ]
