# Generated by Django 2.0.2 on 2018-02-27 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_board_app', '0010_auto_20180227_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='square',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='square', to='game_board_app.Entity'),
        ),
    ]
