# Generated by Django 2.0.2 on 2018-02-27 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_board_app', '0012_auto_20180227_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='square',
            name='entity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='square', to='game_board_app.Entity'),
        ),
    ]
