# Generated by Django 2.0.2 on 2018-02-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_board_app', '0013_auto_20180227_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='health',
            field=models.IntegerField(default=10),
        ),
    ]
