# Generated by Django 2.0.2 on 2018-02-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_board_app', '0014_auto_20180228_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='health',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
