# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_board_app', '0015_entity_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hosted_games',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host', to='game_board_app.Game'),
        ),
    ]
