# Generated by Django 2.0.2 on 2018-03-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_board_app', '0016_player_hosted_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='resources',
            field=models.IntegerField(default=50),
        ),
    ]
