# Generated by Django 2.0.2 on 2018-03-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_board_app', '0017_player_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='health',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='entity',
            name='kind',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='entity',
            name='level',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='health',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='resources',
            field=models.IntegerField(),
        ),
    ]
